update to 1.0.10
AnacondaRecipes/snowflake-ml-python-feedstock pull request #11
Opened 2023-10-17 12:18 UTC by M-Waszkiewicz-Anaconda

- update to 1.0.10
- [requirements](https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.10/requirements.yml)

2023-10-17 12:19 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:42: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-17 12:22 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:41: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-17 12:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:41: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-17 13:10 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:41: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-18 06:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:41: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-18 06:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-18 15:07 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-18 20:04 UTC, M-Waszkiewicz-Anaconda commented
Build succesfuly on windows local machine:

```

(base) %SRC_DIR%>conda activate "%PREFIX%"
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'

Resource usage statistics from testing snowflake-ml-python:
   Process count: 1
   CPU time: Sys=-, User=-
   Memory: 4.2M
   Disk usage: 1.5K
   Time elapsed: 0:00:02.1


TEST END: C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.0.10-py311h2bbff1b_0.tar.bz2
Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work_moved_snowflake-ml-python-1.0.10-py311h2bbff1b_0_win-64_main_build_loop'
INFO:conda_build.utils:Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work_moved_snowflake-ml-python-1.0.10-py311h2bbff1b_0_win-64_main_build_loop'
shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work_moved_snowflake-ml-python-1.0.10-py311h2bbff1b_0_win-64_main_build_loop)
INFO:conda_build.utils:shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\work_moved_snowflake-ml-python-1.0.10-py311h2bbff1b_0_win-64_main_build_loop)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1697645863918\_build_env\Library\lib\modules.  Please remove this file manually (you may need to reboot to free file handles)
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
anaconda upload ^
    C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.0.10-py311h2bbff1b_0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "snowflake-ml-python-1.0.10-py311h2bbff1b_0": {
    "recipe": {
      "c_compiler": "vs2017",
      "channel_targets": "defaults",
      "target_platform": "win-64"
    }
  }
}


####################################################################################
Resource usage summary:

Total time: 0:12:04.7
CPU usage: sys=0:00:38.2, user=0:01:49.0
Maximum memory usage observed: 914.8M
Total disk usage observed (not including envs): 15.5G


####################################################################################
Source and build intermediates have been left in C:\Users\48667\miniconda3\conda-bld.
There are currently 8 accumulated.
To remove them, you can run the ```conda build purge``` command
```

2023-10-18 21:05 UTC, JeanChristopheMorinPerso requested changes

2023-10-18 21:05 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - sentencepiece >=0.1.95,<0.2
sentencepiece is already in `run_constrained`.

2023-10-18 21:05 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pytimeparse >=1.1.8,<2
You already added it above at line 40.

2023-10-18 21:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-18 21:55 UTC, danpetry approved these changes
A couple of optional suggestions

2023-10-18 21:55 UTC, danpetry commented on recipe/meta.yaml
> +    - pytimeparse>=1.1.8,<2
```suggestion
    - pytimeparse >=1.1.8,<2
```

2023-10-18 21:55 UTC, danpetry commented on recipe/meta.yaml
>      - pip
would you consider including the upstream test suite?

2023-10-18 22:04 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
>      - pip
not sure, the upstream is done by snowflake itself, they test is thoughtfully before giving it to us

2023-10-18 22:06 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - pip
We already talked about this in the past (a couple of times) and upstream tests are usually not enough.Running the tests ourselves actually gives us more confidence that the dependencies are functioning as expected.

2023-10-18 22:33 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
>      - pip
there are import tests, they testing dependencies, for the logic correctness snowflake takes full responsibility, and want us to package deliver package nevertheless

2023-10-18 22:51 UTC, danpetry commented on recipe/meta.yaml
>      - pip
For pure python packages, I'd agree, but since we compile this ourselves, we're not actually testing what they've given us. It's entirely possible we build it wrong and something can go wrong at runtime

2023-10-18 22:53 UTC, danpetry commented on recipe/meta.yaml
>      - pip
Even if the build commands are simple, there's a whole environment we define that could affect things

2023-10-19 07:29 UTC, skupr-anaconda approved these changes

2023-10-19 13:21 UTC, M-Waszkiewicz-Anaconda commented
I have tried the tests, but those are integration tests so the whole env is not being set for anaconda,  here are list of failures on windows:
```
FAILED tests/integ/snowflake/ml/extra_tests/column_name_inference_test.py::ColumnNameInferenceTest::test_pandas_interface
FAILED tests/integ/snowflake/ml/extra_tests/column_name_inference_test.py::ColumnNameInferenceTest::test_snowpark_interface
FAILED tests/integ/snowflake/ml/extra_tests/extra_iterative_imputer_test.py::IterativeImputerTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/extra_voting_regressor_test.py::VotingRegressorTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/extra_voting_regressor_test.py::VotingRegressorTest::test_fit_and_compare_results_pandas
FAILED tests/integ/snowflake/ml/extra_tests/grid_search_on_pipeline_test.py::GridSearchCVTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/grid_search_test.py::GridSearchCVTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/grid_search_test.py::GridSearchCVTest::test_invalid_alias_pattern
FAILED tests/integ/snowflake/ml/extra_tests/method_chaining_test.py::TestMethodChaining::test_multiple_infer_method_calls_on_the_same_df
FAILED tests/integ/snowflake/ml/extra_tests/non_numeric_target_test.py::NonNumericTargetTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/pipeline_with_ohe_and_xgbr_test.py::GridSearchCVTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/extra_tests/pipeline_with_ohe_and_xgbr_test.py::GridSearchCVTest::test_fit_and_compare_results_pandas
FAILED tests/integ/snowflake/ml/extra_tests/pipeline_with_ohe_and_xgbr_test.py::GridSearchCVTest::test_fit_and_compare_results_pandas_dataframe
FAILED tests/integ/snowflake/ml/extra_tests/pipeline_with_ohe_and_xgbr_test.py::GridSearchCVTest::test_pipeline_export
FAILED tests/integ/snowflake/ml/extra_tests/pipeline_with_ohe_and_xgbr_test.py::GridSearchCVTest::test_pipeline_with_limited_number_of_columns_in_estimator_export
FAILED tests/integ/snowflake/ml/extra_tests/quoted_identifier_test.py::QuotedIdentifierTest::test_sp_quoted_identifier_modeling0
FAILED tests/integ/snowflake/ml/extra_tests/quoted_identifier_test.py::QuotedIdentifierTest::test_sp_quoted_identifier_modeling1
FAILED tests/integ/snowflake/ml/extra_tests/randomized_search_test.py::GridSearchCVTest::test_fit_and_compare_results
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_base_double_quoted_identifiers
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_fit_input_cols_check
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_to_sklearn
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_transform_input_cols_check
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_transform_output_cols_check
FAILED tests/integ/snowflake/ml/modeling/framework/base_test.py::TestBaseFunctions::test_validate_data_has_no_nulls
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit_all_missing
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit_all_missing_categorial_keep_empty_features_false
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit_all_missing_keep_missing_false
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit_constant
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_fit_constant_no_fill_numeric
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_inconsistent_input_col_type
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_reset
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_serde
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_sklearn
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_sklearn_constant_string
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_missing_values_not_nan
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_most_frequent_strategy_categorical
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_most_frequent_strategy_categorical_mixed_types
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_most_frequent_strategy_numeric
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_output_columns_one_equal_to_input_column
FAILED tests/integ/snowflake/ml/modeling/impute/simple_imputer_test.py::SimpleImputerTest::test_transform_snowpark_output_columns_same_as_input_columns
FAILED tests/integ/snowflake/ml/modeling/metrics/accuracy_score_test.py::AccuracyScoreTest::test_normalized0
FAILED tests/integ/snowflake/ml/modeling/metrics/accuracy_score_test.py::AccuracyScoreTest::test_sample_weight0
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_invalid_params0
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_invalid_params1
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_invalid_params2
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_labels0
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_normalize0
FAILED tests/integ/snowflake/ml/modeling/metrics/confusion_matrix_test.py::ConfusionMatrixTest::test_sample_weight0
FAILED tests/integ/snowflake/ml/modeling/metrics/correlation_test.py::CorrelationTest::test_with_large_num_of_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/correlation_test.py::CorrelationTest::test_with_large_num_of_rows
FAILED tests/integ/snowflake/ml/modeling/metrics/correlation_test.py::CorrelationTest::test_with_nans
FAILED tests/integ/snowflake/ml/modeling/metrics/correlation_test.py::CorrelationTest::test_with_selected_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/correlation_test.py::CorrelationTest::test_with_string_and_numeric_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_ddof
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_large_num_of_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_large_num_of_rows
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_nans
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_selected_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/covariance_test.py::CovarianceTest::test_with_string_and_numeric_cols
FAILED tests/integ/snowflake/ml/modeling/metrics/d2_absolute_error_score_test.py::D2AbsoluteErrorScoreTest::test_metric_size_threshold
FAILED tests/integ/snowflake/ml/modeling/metrics/d2_absolute_error_score_test.py::D2AbsoluteErrorScoreTest::test_multilabel
FAILED tests/integ/snowflake/ml/modeling/metrics/d2_absolute_error_score_test.py::D2AbsoluteErrorScoreTest::test_multioutput0
FAILED tests/integ/snowflake/ml/modeling/me [...]

2023-10-19 13:26 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-19 14:08 UTC, danpetry commented
yeah, fair enough. Thanks for trying

2023-10-19 14:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>

2023-10-19 20:24 UTC, merged

2023-10-19 20:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:40: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
Errors were found

</details>