update to 1.2.1
AnacondaRecipes/snowflake-ml-python-feedstock pull request #18
Opened 2024-02-05 10:10 UTC by M-Waszkiewicz-Anaconda

snowflake-ml-python 1.2.1

[ticket](https://anaconda.atlassian.net/browse/PKG-3949)
[diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.0...1.2.1#diff-5edc2578758a214f70cba8305755573302cfc4a2125cc756e62949bb3eb9f924)

2024-02-08 15:24 UTC, M-Waszkiewicz-Anaconda commented
windows build passed on my local machine:
```
(base) %SRC_DIR%>conda activate "%PREFIX%"
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'
import: 'snowflake.ml'
import: 'snowflake.ml.fileset'
import: 'snowflake.ml.model'
import: 'snowflake.ml.modeling'
import: 'snowflake.ml.registry'
import: 'snowflake.ml.utils'

Resource usage statistics from testing snowflake-ml-python:
   Process count: 2
   CPU time: Sys=0:00:00.2, User=0:00:00.3
   Memory: 95.1M
   Disk usage: 1.5K
   Time elapsed: 0:00:04.1


TEST END: C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.2.1-py311h2bbff1b_0.tar.bz2
Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work_moved_snowflake-ml-python-1.2.1-py311h2bbff1b_0_win-64_main_build_loop'
INFO:conda_build.utils:Renaming work directory 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work' to 'C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work_moved_snowflake-ml-python-1.2.1-py311h2bbff1b_0_win-64_main_build_loop'
shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work_moved_snowflake-ml-python-1.2.1-py311h2bbff1b_0_win-64_main_build_loop)
INFO:conda_build.utils:shutil.move(work)=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work, dest=C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\work_moved_snowflake-ml-python-1.2.1-py311h2bbff1b_0_win-64_main_build_loop)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename C:\Users\48667\miniconda3\conda-bld\snowflake-ml-python_1707400016462\_build_env\Library\lib\modules.  Please remove this file manually (you may need to reboot to free file handles)
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
anaconda upload ^
    C:\Users\48667\miniconda3\conda-bld\win-64\snowflake-ml-python-1.2.1-py311h2bbff1b_0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "snowflake-ml-python-1.2.1-py311h2bbff1b_0": {
    "recipe": {
      "c_compiler": "vs2017",
      "channel_targets": "defaults",
      "target_platform": "win-64"
    }
  }
}


####################################################################################
Resource usage summary:

Total time: 0:15:23.0
CPU usage: sys=0:00:52.2, user=0:02:25.8
Maximum memory usage observed: 1.0G
Total disk usage observed (not including envs): 15.4G

```

2024-02-09 16:42 UTC, JeanChristopheMorinPerso requested changes

2024-02-09 16:42 UTC, JeanChristopheMorinPerso commented on recipe/0001-use-default-shell-env.patch
> +Subject: [PATCH] use default shell env
Where is this patch coming from? Please add that information in the patch description.

2024-02-09 16:42 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - build 0.10.0
Do they really want a version _that_ strict? And from what I see, it's used during build (since it's basically used to create wheels and sdists). https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.0..1.2.1#diff-dd88476c09e220d4a2381853ede029209665e585fca542dc4fa66fcd4fc147ddR246-R264 and https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.0..1.2.1#diff-147d9431cc3b86241e3b0311eaf5b9336c4cd220ed6d49c655ab842d238507c8R4-R13.

Also note that it's nowhere to be seen in https://inspector.pypi.io/project/snowflake-ml-python/1.2.1/packages/ed/1f/7bc9947289c05ea23522906a789ac947f3f89bd929b1d3313c7e3dd79845/snowflake_ml_python-1.2.1-py3-none-any.whl/snowflake_ml_python-1.2.1.dist-info/METADATA#line.235.

2024-02-09 16:42 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - types-toml 0.10.8.6
Same here, do they really want them _that_ strict? Frmo what I see you have taken these from https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.0..1.2.1#diff-4a9869d190b7f3dc192e802e3a6ba6b7050298113c02b7fe6cd8835d8c75954b, which are environments and not `meta.yml` files.

Doesn't seems to be used and it's also not part of the metadata in https://inspector.pypi.io/project/snowflake-ml-python/1.2.1/packages/ed/1f/7bc9947289c05ea23522906a789ac947f3f89bd929b1d3313c7e3dd79845/snowflake_ml_python-1.2.1-py3-none-any.whl/snowflake_ml_python-1.2.1.dist-info/METADATA#line.235.

2024-02-09 16:56 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
> +    - build 0.10.0
ok, I have overlooked it, it is build dependency only

2024-02-09 16:56 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
> +    - types-toml 0.10.8.6
similar, build dependency only

2024-02-09 16:58 UTC, M-Waszkiewicz-Anaconda commented on recipe/0001-use-default-shell-env.patch
> +Subject: [PATCH] use default shell env
I have generated myself, the hint  was provided on slack by snowflake and I can confirm without it windows build fails

2024-02-09 17:04 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - pip
`peft >=0.5.0,<1` is missing from `run_constrained`. And I'm also wondering if we still need `anyio`...

2024-02-09 17:48 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - pip
I'm sorry, I meant aiohttp.

2024-02-09 18:11 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
>      - pip
yes, if it is in `version_requirements_conda` then we need to have it, opposite to `version_requirements_pypi`

2024-02-09 19:03 UTC, danpetry commented on recipe/meta.yaml
>      - pip
Wondering why aiohttp wouldn't be necessary? This package seems to want the http functionality from fsspec, judging by the comment in requirements.yml

2024-02-09 19:04 UTC, JeanChristopheMorinPerso approved these changes

2024-02-09 19:06 UTC, danpetry commented on recipe/meta.yaml
>    host:
upstream added `build`, `toml` and `types-toml` to `build_essential`, are they needed?

2024-02-09 19:08 UTC, danpetry commented on recipe/meta.yaml
>    host:
or whatever our `types-toml` package is

2024-02-09 19:08 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>    host:
I think it'll be needed in `host` yes.

2024-02-09 19:10 UTC, danpetry commented on recipe/0001-use-default-shell-env.patch
> +Subject: [PATCH] use default shell env
it would be nice to get a bit more explanation imho... something like "the build fails on powershell giving x error so we need to run this in cmd" or whatever

2024-02-09 19:17 UTC, danpetry commented on recipe/meta.yaml
>    host:
It looks like these were added at first, then taken out to solve the following error (e.g. on linux-64:
```
None INFO FileNotFoundError: [Errno 2] No such file or directory: '/croot/snowflake-ml-python_1707401386979/work/bazel-bin/dist/snowflake_ml_python-%PKG_VERSION%-py3-none-any.whl'
```
Just wondering whether %PKG_VERSION% should be populated/why that looks like a windows env variable/why the requirements were eventually taken out

2024-02-09 19:21 UTC, danpetry reviewed
I think it would be pretty nice to copy the symlinked files on Windows so it can be built by the CI.
Also run upstream tests since it's a compiled package. I'm a bit curious about the build_essential deps that got taken out for debugging

2024-02-09 19:26 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
>    host:
they are not needed, the build deps are vendored coming from bazel

2024-02-09 19:30 UTC, M-Waszkiewicz-Anaconda commented
> I think it would be pretty nice to copy the symlinked files on Windows so it can be built by the CI. Also run upstream tests since it's a compiled package. I'm a bit curious about the build_essential deps that got taken out for debugging

The tests are integration test running against snowflake infrastructure, you will need to be snowflake customer I suppose to run them, I have tried on it once spend almost 2 days with no results. Making a symlinks in the feedstock because our CI can not handle it is just hackish workaround. I do not want to spend time on this, especially those links are dynamically created by bazel

2024-02-09 19:40 UTC, M-Waszkiewicz-Anaconda commented on recipe/meta.yaml
>    host:
> It looks like these were added at first, then taken out to solve the following error (e.g. on linux-64:
> 
> ```
> None INFO FileNotFoundError: [Errno 2] No such file or directory: '/croot/snowflake-ml-python_1707401386979/work/bazel-bin/dist/snowflake_ml_python-%PKG_VERSION%-py3-none-any.whl'
> ```
> 
> Just wondering whether %PKG_VERSION% should be populated/why that looks like a windows env variable/why the requirements were eventually taken out

yes, It was a copy-paste mistake from bld.bat, corrected now

2024-02-09 20:52 UTC, danpetry commented on recipe/meta.yaml
>    host:
ok, thanks for the clarification.

2024-02-09 20:54 UTC, danpetry approved these changes
In the pytorch feedstock the symlinks are handled by copying files in bld.bat. Hacky it may be, but it's less hassle than manually building each time

2024-02-09 21:01 UTC, merged