snowflake-ml-python 1.6.2
AnacondaRecipes/snowflake-ml-python-feedstock pull request #36
Opened 2024-09-16 20:55 UTC by psteyer

snowflake-ml-python 1.6.2 

**Destination channel:** Defaults

### Links

- [PKG-5713]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.6.2
- conda_forge:    https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-ml-python/1.6.2
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.6.2

### Explanation of changes:

- new version number

2024-09-17 13:28 UTC, ifitchet commented
`doc_url`: `pyproject.toml` says one thing which redirects to the same place that your value redirects to: `https://docs.snowflake.com/developer-guide/snowflake-ml/overview` -- obviously, double check! 😄

2024-09-17 14:28 UTC, boldorider4 requested changes
https://github.com/snowflakedb/snowflake-ml-python/blob/f50d041522ec34bdb85aef793cab17c4b41f30f4/ci/conda_recipe/meta.yaml#L48

`xgboost >=1.7.3,<2.1`

2024-09-17 15:25 UTC, ifitchet commented
Reading my own code's output a bit more closely:

```
feedstock-tool: +112s: WARNING:  README.md looks a bit short 
```

It gives a suggestion.

```
feedstock-tool: +112s: WARNING:  CODEOWNERS not set 
mkdir -p .github
echo @AnacondaRecipes/psubs > .github/CODEOWNERS
```

Also, `pyproject.toml` is only in the pypi tarball.

2024-09-17 17:08 UTC, lorepirri reviewed
please set the build number to `100` update the pinning of `xgboost>=1.7.3,<2.1`, add codeowner as in previous version and recurrent packages

2024-09-18 07:23 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  number: 100
Could you comment on what's behind choosing this number?

2024-09-18 07:42 UTC, lorepirri commented on recipe/meta.yaml
> +  number: 100
@psteyer 
```suggestion
  # The build number of this package should always start from 100
  # for new versions. For more information ask the CODEOWNERS.
  number: 100
```

2024-09-18 07:43 UTC, lorepirri commented on recipe/meta.yaml
> +  number: 100
thanks, @skupr-anaconda I forgot about it as well

2024-09-18 08:12 UTC, skupr-anaconda approved these changes

2024-09-18 08:54 UTC, lorepirri commented
`osx-arm64` fails because of this https://github.com/pypa/pip/issues/12884 see internal discussion https://anaconda.slack.com/archives/C04QPV5GWBW/p1726643593008439

2024-09-18 11:21 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_91zpjc1lbz/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:98: missing_test_requirement_pip: pip is required in the test requirements.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-09-18 11:24 UTC, lorepirri commented on recipe/meta.yaml
> +    - pip <24.2
```suggestion
    # temporary upper pinning for osx-arm64 fails because of this https://github.com/pypa/pip/issues/12884
    # remove it when there is a better solution
    - pip <24.2  # [arm64]
    - pip
```

2024-09-18 11:33 UTC, psteyer commented on recipe/meta.yaml
> +    - pip <24.2
Thank you! I was just about to add the comment.

2024-09-18 12:45 UTC, lorepirri approved these changes
LGTM, thanks for all the improvements done!

2024-09-18 13:10 UTC, ifitchet approved these changes

2024-09-18 16:38 UTC, lorepirri commented
@boldorider4 I think your suggestions were addressed

2024-09-18 17:41 UTC, boldorider4 approved these changes

2024-09-18 17:49 UTC, merged